### ISSUE TITLE
Testing: Local Contexts Module

### ISSUE THREAD

**Issue by matthewjmckinley** [omeka-s-modules/LocalContexts#2]
Retrieve Local Contexts content (notices & labels) from the Local Contexts Hub API. Assign LC content to display in site footer, as a discrete page block, or save as item metadata, in selected or in all available languages.

Local Contexts test integration account project page:
https://sandbox.localcontextshub.org/communities/view/2/

Local Contexts test integration account API key to use in testing:
T0NsNURnUVIudFJhRVZId1Y2RWJsUldTQllEcWI3VzJLblFmbEJuNjk

Please test:

- Inserting only API key in LC API settings, returning all projects from project page (above) as well as Open to Collaborate notice
- Inserting API key and specific project id(s), separated by comma, returning only content specific to given project(s) as well as Open to Collaborate notice
- Assigning/removing LC content via API settings results
- Submitting API settings with no API key still returns already assigned LC content to remove
- Assigning LC content to site, under Sites->Site Admin->Settings, including selecting single and all languages respectively, and that is displays correctly in site footer in all themes
- Assigning LC content as page block
- Saving LC content as metadata (under Advanced tab) or as batch metadata edit, including selecting metadata field and saving as single & all languages respectively, and that it displays properly (i.e. as HTML with accompanying graphic) on both admin and public side
- Ensure that if more than 3 LC projects are available in all admin side menus (assign, remove, site settings, page block, item edit, batch item edit), that they are hidden under their title in a collapsible div
- Any other test ideas or issues you uncover

Thanks!

**Comment by aviannamiller** [comment]
So far, most aspects are functioning as expected based on the criteria outlined here. I did pick out a few issues with the following: 
> Inserting only API key in LC API settings, returning all projects from project page (above) as well as Open to Collaborate notice

- I am not exactly returning all of the projects from the project page. Only the following eleven projects resulted: <img width="1016" alt="Assign page with eleven items and corresponding checkboxes, all listed in collapsible divs" src="https://github.com/user-attachments/assets/995c6cd0-3433-48bc-b7aa-5e1aa6e7bed7" />

- From the module dashboard, project links open in the same tab. If you want to then easily return back to the assign page after activating the link, you get a form resubmission error. Can these open in separate tabs like they do when interacting with links on LC content that is added to a site (via either footer or page block)?

> Assigning LC content to site, under Sites->Site Admin->Settings, including selecting single and all languages respectively, and that is displays correctly in site footer in all themes

- LC content is displaying correctly in the footer for all themes except for Freedom and Lively. Freedom is styling accompanying text as #ffffff on the #ffffff background:
<img width="1265" alt="LC content in Freedom footer. There are LC graphics next to white space, which is revealed to be white text through a highlighted portion of text. There are orange language tags for each item" src="https://github.com/user-attachments/assets/2e04b64b-85b3-41f7-823c-7d0f661002ff" />  While Freedom does not have this contrast issue, this theme illuminates a spacing issue with the text and language tags. It would be great to have some breathing room between the two (the same is true for Lively once the more glaring contrast issue is addressed): <img width="1253" alt="LC content in Lively footer. White text on a purple background. There are language tags for each item inserted on top of the content's text descriptions" src="https://github.com/user-attachments/assets/a7803b98-d7d5-499e-9017-2aad422d96ee" />

> Saving LC content as metadata (under Advanced tab) or as batch metadata edit, including selecting metadata field and saving as single & all languages respectively, and that it displays properly (i.e. as HTML with accompanying graphic) on both admin and public side

- LC content mostly looks okay assigned as item metadata, although the project descriptions are hyperlinking out to, in our case, https:// dev. omeka. org. Is this supposed to happen? <img width="845" alt="Item page for Test item 1 (LC). Metadata includes descriptions from LC content, all of which is appearing as hyperlinked text" src="https://github.com/user-attachments/assets/baefbe31-62f8-4f9e-bad7-25d4baa26c80" />

Some other observations:

- In the LC module, after initiating a page return to the initial settings page from the assign/remove page, only the project IDs remain in the text field, not the API key. Would it be possible to have the key remain in the field there as well when going back to the page in case edits are needed in a given session?
- Entering multiples of the same project ID causes multiples of that project to show up in the assign list, although selecting duplicates only assigns the project once. Is there a way to ensure only one of that project would show up in the assign list even if the same ID is entered multiple times (though maybe this is less important since only one can be assigned anyway)?
- When collapsible divs do appear, the expand/collapse announcement is a bit iffy across screen readers. I am not always getting the collapse read out. Perhaps `aria-expanded` should be implemented here?

**Comment by matthewjmckinley** [comment]
Hi @aviannamiller , thank you for this! Issues, in order:

- (fixed) All projects should be returning now--I implemented a pagination iterator in the API results
- (fixed) This was a small bug, project links should open in a new tab from all pages
- (open) I've tried several ways to put more space between the title and language for Freedom and Lively, but none worked quite right. Same with the text contrast--I'm just not sure how to specify a text color change for one theme but not all the others. I'm going to create a sub-issue for theme display issues and ping Kim and Nelson.
- (fixed) the self-referring hyperlink was also a bug, should be fixed now.
- (kinda-fixed) The API key is technically a password, and it's a security no-no to store in the database if it can be at all avoided, so I can't save and serve up the API key again in the actual form field. However, I did a fix that re-passes the API key as a hidden input to the assign page, meaning for both S and Classic, when projects are added and/or removed and the Submit key is pressed, the new projects pulled from the API should persist (previously, it only listed the 'local' projects to delete after the Submit key was pressed).
- (fixed) I've fixed this by de-duplicating the project ID array before it fetches content from the API
- (open) I tried adding `aria-expanded` to the collapse div, and it isn't responsive like it is in other places. Looks like the toggle to make `aria-expanded` true/false is missing from the global.js file. I'll mention that in the theming sub-issue above.

**Comment by aviannamiller** [comment]
Thanks so much for these fixes! Having the projects (after initially being pulled from the API key) persist on the assign page after submitting assign/remove is a great solution to that issue and working as expected.

Just a few issues remain:

- > (fixed) All projects should be returning now--I implemented a pagination iterator in the API results
  - I am now getting what appears to be all projects on the Local Contexts Projects Board (seeing ~105 projects+notice), not just those from the Southwest Community project page.

- > (fixed) the self-referring hyperlink was also a bug, should be fixed now.
  - Hmm, I am still seeing the same issue on both admin and public sides.

- > (fixed) I've fixed this by de-duplicating the project ID array before it fetches content from the API
  - Listing multiple of the same ID in the form is still fetching a duplicate, though the behavior is a bit different now. Any number of duplicate IDs submitted seems to only fetch up to one duplicate (so two of the same will list in results), and if multiple distinct project IDs are entered as duplicates, only one of the projects will result in a duplicate in the assign list. 

    <img width="1015" alt="List of six LC projects to assign. Two are duplicates of the same project." src="https://github.com/user-attachments/assets/83b3b166-dc6d-431e-ba55-56fa4016b50c" />

    In this example, the following project IDs were entered: 
    d09f99d8-179a-4f9e-8714-c45bddc37662, d09f99d8-179a-4f9e-8714-c45bddc37662, d09f99d8-179a-4f9e-8714-c45bddc37662, 04b2638e-4c9c-4144-8902-feb65a0abb90, d77e3ee3-3503-4118-8863-dee910e05692, d77e3ee3-3503-4118-8863-dee910e05692, d77e3ee3-3503-4118-8863-dee910e05692, 6de7e208-68de-497f-a624-07b630780267, 6de7e208-68de-497f-a624-07b630780267, 6de7e208-68de-497f-a624-07b630780267

**Comment by matthewjmckinley** [comment]
- I am now getting what appears to be all projects on the Local Contexts Projects Board (seeing ~105 projects+notice)

Ah sorry, this is something I had to clarify with the LC developer as well -- so I guess the API account I gave you is for a test Integration Partner account. Integration Partners are groups (such as Omeka) that work with multiple institutions or researchers, and as such need wide access to projects via the API, not just the projects associated with their account. Institutions/Researchers/etc. (i.e. our users) will only see projects associated with their Institution or Researcher account, respectively. You can test this with this API key `dGNVNEZJOGUuQVlSTWQyQnN6b0RuZ1FyU0QwWExPbEJJVGJoYzNuM08`, which should only return projects associated with the Sample Institution account https://sandbox.localcontextshub.org/institutions/view/1/
(you will notice however that there are a few extra projects being fetched that aren't on the Sample Institution page -- 2025 Seed Catalog, for example -- that are returned in the fetched API results. Sample Institution was added as a contributor to these projects but they themselves did not create them, hence them not showing up on their Sample Institution page. Kinda confusing, I know, but thats how some things have rolled while working with this team)

- Hmm, I am still seeing the same issue on both admin and public sides.

I suspect you're clicking on metadata values that you previously added with the older code. You'll need to remove those older values where the linking was done correctly and/or test on freshly applied metadata values to see the change in the hyperlinking show up. Since the hyperlinks are saved as HTML directly to the metadata field, they aren't dynamically changed the same way code updates to other parts of the LC module might be.

- Dedupe behavior: my bad, I guess I left off a flag to specify the comparison values as numeric, and it was still returning some duplicates as you saw. Should be fixed with latest pushed commit.

**Comment by aviannamiller** [comment]
Great, the hyperlinks in metadata look good on both sides. I'm not seeing any remaining issues on my end besides `aria-expanded` and those theme-specific ones.

(Thanks as well for your input on the site timeouts, probably just a coincidence.)

**Comment by aviannamiller** [comment]
I just noticed that the last Project IDs that are entered into the API Settings page remain held in the input box indefinitely until a user manually erases them. It's great to have those remain as input when, say, a user initiates a page return from the assign/remove page (as previously discussed), but I'm not sure that it makes sense to store them beyond that.

(Sorry, I know I had said no remaining issues!)

**Comment by aviannamiller** [comment]
Got it. Thanks for looking it; I agree with not having the IDs persist as I definitely see that requiring an odd workflow to work, and maintaining the IDs as they are now overcomplicates things a bit for certain user purposes (e.g. navigating to the remove screen or viewing all projects for a given key).

**Comment by matthewjmckinley** [comment]
`autocomplete="off"` incorporated into input form with latest commit

**Comment by aviannamiller** [comment]
Great, that update looks good on Firefox and Safari. Still getting autocomplete behavior on Chrome, so that just seems to be a browser-specific issue.

**Comment by aviannamiller** [comment]
There are some label issues I have just encountered:

- When there are less than three projects listed (and notices are no longer under collapsible divs), checkboxes lose their labels / no longer have accessible names for assistive tech.
- For site settings and batch edit, the Language `select` does not have a matching id to the "for" attribute on the label, so that label is not being picked up by assistive tech.
  - Same issue for Property and Language `select` on item edit pages.
- On batch edit, why is the label for selecting a property "Local Contexts field" instead of "Local Contexts property" as it is on item edit pages?

**Comment by matthewjmckinley** [comment]
All admin-side LC content collapsible by default (just like classic) and updated the attributes and labels mentioned above in latest commits.

**Comment by aviannamiller** [comment]
Great, that looks good. Thank you!

**Comment by matthewjmckinley** [comment]
@aviannamiller whoops meant to post here--have all the major issues been resolved for release, pending documentation?

**Comment by matthewjmckinley** [comment]
Good catch, fixed with latest commit.

Reviewing the issues for both the plugin and the module, it seems like we're pretty good to go for initial release. Does mid next week sound good? I'll notify Ashley if so.

**Comment by allanaaa** [comment]
Great, so the whole LC option doesn't load on the Advanced tab in item editing, or in the site settings, when you have no projects assigned. (Unless you have a legacy project already set in the site footer.)

When there are no projects, the page block is still visible, but gives an "error" (No content set). The page block will still load on public pages (as a zero-pixel div). 

<img width="906" height="88" alt="Image" src="https://github.com/user-attachments/assets/4b82ccbf-2a8f-48be-8dee-7c8c957649c4" />

We *might* not want to give the page block as an option at all when there are no projects assigned to the installation? But I think this is probably fine. 

I think that was the only thing I noticed when doing the documentation. Kim pinpointed a weird interaction between the LC and the Metadata Browse module, so I'm going to note that in the docs.

**Comment by allanaaa** [comment]
Not a problem.
